=== lrag/XML/Ej04_DOM/WebContent/peliculas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="http://www.example.org/peliculas" 
		xmlns:tns="http://www.example.org/peliculas" 
		elementFormDefault="qualified">
		
	<!-- 
	<element name="peliculas">
		<complexType>
			<sequence>
				<element name="pelicula" minOccurs="0" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="titulo"   type="string" />
							<element name="director" type="string" />
							<element name="genero"   type="string" />
							<element name="year"     type="integer" />
						</sequence>
						<attribute name="id" use="required" type="integer"/>
					</complexType>
				</element>	
			</sequence>
		</complexType>
	</element>
	-->
		
	<complexType name="pelicula">
		<sequence>
			<element name="titulo"   type="string" />
			<element name="director" type="string" />
			<element name="genero"   type="string" />
			<element name="year"     type="integer" />
		</sequence>
		<attribute name="id" use="required" type="integer"/>
	</complexType>

	<element name="peliculas">
		<complexType>
			<sequence>
				<element name="pelicula" minOccurs="0" maxOccurs="unbounded" type="tns:pelicula"/>
			</sequence>
		</complexType>
	</element>	
		
</schema>

=== lrag/XML/Ej04_DOM/WebContent/peliculas.xml
<?xml version="1.0" encoding="UTF-8"?>


<peliculas xmlns="http://www.example.org/peliculas"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.example.org/peliculas peliculas.xsd">
	
	<pelicula id="1">
		<titulo>2001</titulo>
		<director>Stanley Kubrik</director>
		<genero>CiFi</genero>
		<year>1968</year>
	</pelicula>
	<pelicula id="2">
		<titulo>Alien</titulo>
		<director>Ridley Scott</director>
		<genero>CiFi</genero>
		<year>1979</year>
	</pelicula>
	<pelicula id="3">
		<titulo>Die Hard</titulo>
		<director>John Mctiernan</director>
		<genero>Acción</genero>
		<year>1988</year>
	</pelicula>
	<pelicula id="4">
		<titulo>El jovencito Frankenstein</titulo>
		<director>Mel Brooks</director>
		<genero>Comedia</genero>
		<year>1974</year>
	</pelicula>
	<pelicula id="5">
		<titulo>Mad Max fury road</titulo>
		<director>George Miler</director>
		<genero>Acción</genero>
		<year>2015</year>
	</pelicula>
	<pelicula id="6">
		<titulo>AAA</titulo>
		<director>BBB</director>
		<genero>CCC</genero>
		<year>2017</year>
	</pelicula>
	
</peliculas>
