=== lrag/XML/Ej03_XSD/WebContent/XML/xmlSchemaDefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
xmlns: los elementos y tipos de datos utilizados en un xsd están
       definidos en http://www.w3.org/2001/XMLSchema
       Al no indicar prefijo es el espacio de nombres por defecto
targetNameSpace: indicamos el nombre del espacion de nombres que estamos definiendo
xmlns:tns : asignamos el prefijo 'tns' al espacio de nombres de estamos definiendo      
-->

<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://www.example.org/xmlSchemaDefinition" 
        xmlns:tns="http://www.example.org/xmlSchemaDefinition"
        elementFormDefault="qualified">
        
	<!-- 
	Elementos simples
	Solo pueden contener un valor, no otras etiquetas
	No tienen atributos
	<element name="xxx" type="yyy"/>
	-->        
	
	<!-- 
	-->
	<element name="raiz"/>
	
	<!-- 
	Tipos (muchos más):
	
	string
	decimal
	integer
	boolean
	date (2017-01-31)
	time
	 -->
	
	<element name="nombre" type="string"/>
	<element name="altura" type="decimal"/>
	<element name="cantidad" type="integer"/>
	<element name="fecha" type="date"/>
	
	<!-- 
	Valores por defecto y fijos
	-->
	<element name="colorTexto" type="string" default="rojo"/>
	<element name="colorFondo" type="string" fixed="blanco"/>
	 
	<!-- 
	Restricciones en los valores
		
	enumeration	    Defines a list of acceptable values
	fractionDigits	Specifies the maximum number of decimal places allowed. Must be equal to or greater than zero
	length	        Specifies the exact number of characters or list items allowed. Must be equal to or greater than zero
	maxExclusive	Specifies the upper bounds for numeric values (the value must be less than this value)
	maxInclusive	Specifies the upper bounds for numeric values (the value must be less than or equal to this value)
	maxLength	    Specifies the maximum number of characters or list items allowed. Must be equal to or greater than zero
	minExclusive	Specifies the lower bounds for numeric values (the value must be greater than this value)
	minInclusive	Specifies the lower bounds for numeric values (the value must be greater than or equal to this value)
	minLength	    Specifies the minimum number of characters or list items allowed. Must be equal to or greater than zero
	pattern	        Defines the exact sequence of characters that are acceptable
	totalDigits	    Specifies the exact number of digits allowed. Must be greater than zero
	whiteSpace	    Specifies how white space (line feeds, tabs, spaces, and carriage returns) is handled	
	-->      
	
	<!-- min-max -->
	<element name="anchura">
		<simpleType>
			<restriction base="integer">
				<minInclusive value="0"/>
				<maxInclusive value="10"/>
			</restriction>
		</simpleType>	
	</element>
		      
	<!-- Enumeración de valores -->
	<element name="coche">
		<simpleType>
			<restriction base="string">
				<enumeration value="Simca" />
				<enumeration value="Authi" />
				<enumeration value="Talbot" />
			</restriction>
		</simpleType>
	</element>	      

	<!-- Patrones -->
	<element name="letraMinuscula">
		<simpleType>
			<restriction base="string">
				<pattern value="[a-z,ñ]-[0-9]" />
			</restriction>
		</simpleType>
	</element>
	<element name="password">
		<simpleType>
			<restriction base="string">
				<pattern value="[a-zA-Z0-9]{8}" />
			</restriction>
		</simpleType>
	</element>
		        
	<!-- Longitud -->
	<!-- 
	Espacios en blanco 
	Espacios, tabuladores, saltos de línea y retornos de carro
    <restriction base="string">
	    <whiteSpace value="preserve"/>
    </restriction>
    <restriction base="string">
    	<whiteSpace value="replace"/>
    </restriction>
    <restriction base="string">
    	<whiteSpace value="collapse"/>
    </restriction>	
	-->	    
	
	<!-- 
	Elementos complejos

	ComplexType anónimo:
	-->
	<element name="empleado">
		<complexType>
			<sequence>
				<element name="nombre" type="string" />
				<element name="apellidos" type="string" />
			</sequence>
		</complexType>
	</element>	

	<!-- 
	Reutilizando un complexType 
	-->	
	<complexType name="persona">
		<sequence>
			<element name="nombre" type="string"/>
			<element name="apellidos" type="string"/>
		</sequence>
	</complexType>	
	
	<element name="profesor" type="tns:persona"/>
	<element name="alumno" type="tns:persona"/>

	<!-- Otro ejemplo de complexType reutilizado: -->
	<complexType name="cliente">
		<sequence>
			<element name="nombre" type="string" />
			<element name="direccion" type="string" />
		</sequence>
	</complexType>

	<element name="factura">
		<complexType>
			<sequence>
				<element name="codigo" type="string" />
				<element name="cliente" type="tns:cliente"/>
				<element name="formaPago" type="string"/>
			</sequence>
		</complexType>
	</element>

	<element name="pedido">
		<complexType>
			<sequence>
				<element name="codigo" type="string" />
				<element name="cliente" type="tns:cliente"/>
				<element name="observaciones" type="string"/>
			</sequence>
		</complexType>
	</element>

	<!-- 
	Herencia de complex types
	-->

	<element name="camion" type="tns:vehiculoCarga" />
	<element name="moto" type="tns:vehiculo" />

	<complexType name="vehiculo">
		<sequence>
			<element name="marca" type="string" />
			<element name="modelo" type="string" />
		</sequence>
	</complexType>

	<complexType name="vehiculoCarga">
		<complexContent>
			<extension base="tns:vehiculo">
				<sequence>
					<element name="volumenCarga" type="double" />
					<element name="pesoCarga" type="double" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>		        
		        
	<!-- 
	Atributos
	<attribute name="xxx" type="yyy"/>	

	Valores por defecto y fijos

	<attribute name="idioma" type="string" default="ES"/>
	<attribute name="idioma" type="string" fixed="ES"/>
	
	Atributo obligatorio
	<attribute name="id" use="optional" type="positiveInteger" /> (por defecto son optional)
	<attribute name="id" use="required" type="positiveInteger" />
	-->

	<!-- 
	ComplexType vacío, pero con atributos
	-->
	<element name="producto">
		<complexType>
			<attribute name="id" use="required" type="positiveInteger"/>
			<attribute name="fabricante" use="required" type="string"/>
		</complexType>
	</element>
	
	<!-- 
	ComplexType con atributos y solo texto
	-->
	<element name="recordatorio">
		<complexType>
			<simpleContent>
				<extension base="string">
					<attribute name="idEmpleado" type="integer" />
				</extension>
			</simpleContent>
		</complexType>
	</element>	
	
	<!-- 
	ComplexType con atributos e hijos
	Primero la secuencia y despues los atributos
	-->
	<element name="libro">
		<complexType>
			<sequence>
				<element name="titulo" type="string"/>
				<element name="autor" type="string"/>
			</sequence>
			<attribute name="ISBN" type="string"/>
		</complexType>
	</element>	
	
	<!-- 
	Mezcla de texto y elementos hijos

	<complexType mixed="true">

	<carta>
		Estimado Sr.<nombre>Venkman</nombre>.
		Su pedido <codPedido>1032</codPedido>
		será enviado el día <fecha>2017-07-13</fecha>
	</carta>
	-->
	
	<element name="carta">
	  <complexType mixed="true">
	    <sequence>
	      <element name="nombre" type="string"/>
	      <element name="codPedido" type="positiveInteger"/>
	      <element name="fecha" type="date"/>
	    </sequence>
	  </complexType>
	</element>	
	
	<!-- 
	Indicadores

	Número de ocurrencias:
	maxOccurs
	minOccurs

	Grupos:
	Group 
	attributeGroup 
	
	Otros:
	All      : los elementos en cualquier orden
	Choice   : uno de los elementos presentes
	Sequence : elementos en un orden concreto
	-->

	<!-- 
	Indicadores: Ocurrencias 
	-->
	<element name="documento">
		<complexType>
			<sequence>
				<element name="creador" type="string" />
				<element name="validador" type="string" maxOccurs="unbounded" />
				<element name="notas" type="string" minOccurs="0" maxOccurs="1"/>
			</sequence>
		</complexType>
	</element>  
	
	<!-- 
	Indicadores: grupos de elementos
	
	Permiten definir una serie de elementos que añadir después a otras secuencias
	-->

	<group name="datosDireccion">
		<sequence>
			<element name="ciudad" type="string"/>		
			<element name="calle" type="string"/>		
			<element name="numero" type="string"/>		
		</sequence>
	</group>
	
	<element name="cliente">
		<complexType>
			<sequence>
				<element name="nombre" type="string"/>
				<group ref="tns:datosDireccion"/>
			</sequence>		
		</complexType>
	</element>	

	<!-- 
	Puede parecer que los grupos son lo mismo que los complex types:
	un grupo no tiene una etiqueta que rodea la secuencia.	
	<complexType name="direccion">
		<sequence>
			<element name="ciudad" type="string"/>		
			<element name="calle" type="string"/>		
			<element name="numero" type="string"/>		
		</sequence>
	</complexType>	
	<element name="cliente2">
		<complexType>
			<sequence>
				<element name="nombre" type="string"/>
				<element name="direccion" type="tns:direccion"/>
			</sequence>		
		</complexType>
	</element>	
	-->	

	<!-- 
	Indicadores: Grupos de atributos
	-->
	<attributeGroup name="metadatos">
		<attribute name="fechaCreacion" type="date" />	
		<attribute name="fechaModificacion" type="date" use="required"/>	
		<attribute name="fechaAcceso" type="date"/>	
	</attributeGroup>
	
	<element name="post">
		<complexType>
			<sequence>
				<element name="autor" type="string"/>			
				<element name="contenido" type="string"/>			
			</sequence>
			<attributeGroup ref="tns:metadatos"/>
		</complexType>
	</element>

	<!-- 
	Indicadores: otros
	
	Sequence : elementos en el orden exacto y una sola vez (si no se indica el número de ocurrencias)
	All: elementos en cualquier orden y como máximo una vez
	-->
	<element name="pelicula">
		<complexType>
			<all>
				<element name="titulo" type="string" />
				<element name="director" type="string" />
			</all>
		</complexType>
	</element>

	<!--
	Choice 
 	-->
 	<element name="disco">
 		<complexType>
			<sequence>
				<element name="titulo" type="string"/>
				<choice>
					<element name="grupo" type="string"/>
					<element name="solista" type="string"/>
					<element name="grupos">
						<complexType>
							<sequence>
								<element name="grupo" type="string" minOccurs="1" maxOccurs="unbounded"/>
							</sequence>
						</complexType>
					</element>
				</choice>			
			</sequence> 		
 		</complexType>
 	</element>
	
	<!-- 
	Any: cualquier etiqueta que esté definida.
	Si no se indica el número de ocurrencias es obligatoria
	-->
	<element name="curso">
		<complexType>
			<sequence>
				<element name="titulo" type="string"/>
				<any/> 
			</sequence>		
		</complexType>
	</element> 
	
	<!-- 
	Substitutiongroup: para tener la misma etiqueta con varios nombres
	-->
	<element name="proveedor">
		<complexType>
			<sequence>
				<element name="nombre"/>
			</sequence>
		</complexType>
	</element>
	<element name="provider" substitutionGroup="tns:proveedor"/>
	
	<!-- 
	Annotations: información asociada al xsd
	-->
	<annotation>
		<appinfo></appinfo>
		<documentation></documentation>
	</annotation>
	        	        
</schema>

=== lrag/XML/Ej03_XSD/WebContent/XML/fichero.xml
<?xml version="1.0" encoding="UTF-8"?>

<raiz xmlns="http://www.example.org/xmlSchemaDefinition"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.example.org/xmlSchemaDefinition xmlSchemaDefinition.xsd">

	<nombre>Bart</nombre>
	<altura>10.5</altura>
	<cantidad>20</cantidad>
	<fecha>2017-05-29</fecha>
	
	<sioque></sioque>

	<colorTexto></colorTexto> <!-- Rojo -->
	<colorTexto>Verde</colorTexto>
	
	<colorFondo></colorFondo>
	<colorFondo>blanco</colorFondo>
	<!-- <colorFondo>azul</colorFondo> -->

	<anchura>10</anchura>
	<coche>Authi</coche>
	
	<letraMinuscula>ñ-9</letraMinuscula>
	<password>12345678</password>

	<empleado>
		<nombre>Bender</nombre>
		<apellidos>Bending Rodriguez</apellidos>
	</empleado>
	
	<profesor>
		<nombre>Luis Ramón</nombre>
		<apellidos>Álvarez González</apellidos>
	</profesor>
	<alumno>
		<nombre>Luis Ramón</nombre>
		<apellidos>Álvarez González</apellidos>
	</alumno>
	
	<camion>
		<marca>Pegaso</marca>
		<modelo>Troner</modelo>
		<volumenCarga>20</volumenCarga>
		<pesoCarga>20</pesoCarga>
	</camion>
	<moto>
		<marca>Yamaha</marca>
		<modelo>FZR</modelo>
	</moto>

	<producto id="123" fabricante="Tal"/>

	<recordatorio idEmpleado="42">
		Texto
	</recordatorio>
	
	<libro ISBN="123">
		<titulo>El quijote</titulo>
		<autor>Cervantes</autor>
	</libro>
	
	<carta>
		Estimado <nombre>Peter Venkman</nombre>.
		Su pedido con código <codPedido>127</codPedido>
		se enviará con fecha <fecha>2017-01-01</fecha>
	</carta>
	
	<documento>
		<creador>Groucho</creador>
		<validador>Harpo</validador>
		<validador>Chico</validador>
		<notas>
			Contrato
		</notas>
	</documento>
	
	<cliente>
		<nombre>Cliente</nombre>
		<ciudad>Madrid</ciudad>
		<calle>C/Barquillo</calle>
		<numero>20</numero>
	</cliente>

	<post fechaCreacion="2017-01-01" fechaModificacion="2017-01-01" fechaAcceso="2017-01-01">
		<autor>Johnny Cab</autor>
		<contenido>
			Bla bla blá
		</contenido>
	</post>
	
	<pelicula>
		<titulo>T1</titulo>
		<director>James Cameron</director>
	</pelicula>
	<pelicula>
		<director>James Cameron</director>
		<titulo>Abyss</titulo>
	</pelicula>

	<curso>
		<titulo>XML</titulo>
		<pelicula>
			<titulo>T1</titulo>
			<director>James Cameron</director>
		</pelicula>
	</curso>
	<curso>
		<titulo>Spring</titulo>
		<moto>
			<marca>Yamaha</marca>
			<modelo>FZR</modelo>
		</moto>		
	</curso>
	
	<proveedor>
		<nombre></nombre>
	</proveedor>
	<provider>
		<nombre></nombre>
	</provider>
	
</raiz>
