=== lrag/XML/Ej02_DTD/src/main/resources/XML/03_atributos.dtd
<!--
<!ATTLIST element-name attribute-name attribute-type attribute-value>
-->

<!ELEMENT cliente EMPTY>
<!ATTLIST cliente id CDATA "0">

<!--
<!ATTLIST element-name attribute-name attribute-type #REQUIRED>
-->

<!ELEMENT producto EMPTY>
<!ATTLIST producto id CDATA #REQUIRED>

<!--
Opcional y sin valor por defecto
<!ATTLIST element-name attribute-name attribute-type #IMPLIED>
-->

<!ELEMENT factura EMPTY>
<!ATTLIST factura pedido CDATA #IMPLIED>

<!--
Con un valor prefijado que no se puede cambiar
<!ATTLIST element-name attribute-name attribute-type #FIXED "valor">
-->

<!ELEMENT raiz ANY>
<!ATTLIST raiz emisor CDATA #FIXED "AppAngularCliente">

<!--
<!ATTLIST element-name attribute-name (v1|v2|..) default-value>
-->

<!ATTLIST factura estado (pendiente|emitida|cobrada) "pendiente">

=== lrag/XML/Ej02_DTD/src/main/resources/XML/03_atributos.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--  
Referenciamos el DTD
<!DOCTYPE etiqueta_raíz SYSTEM "ruta al DTD">
-->
<!DOCTYPE raiz SYSTEM "03_atributos.dtd">

<!-- 
<raiz emisor="movida">
-->
<raiz emisor="AppAngularCliente">

	<cliente></cliente>
	<cliente id="1"></cliente>
	<!-- 
	<cliente id="1" movida="2"></cliente>
	-->
	
	<!-- 
	<producto></producto>
	-->
	<producto id="0"></producto>
	
	<factura></factura>
	<factura pedido="PED-0"></factura>
	
	<factura></factura>
	<factura estado="pendiente"></factura>
	<factura estado="emitida"></factura>
	<factura estado="cobrada"></factura>
	<!-- 
	<factura estado="OTRO"></factura>
	-->
	
	<coche marca="FIAT" modelo="Uno 45s" matricula="M-5000-JP" color="Rojo"/>

</raiz>
