=== lrag/XML/Ej02_DTD/src/main/resources/XML/04_entities.dtd
<!--
<!ENTITY entity-name "entity-value">

Para valores repetidos:
-->

<!ELEMENT raiz ANY>

<!ELEMENT libro (editorial,autor)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT autor (#PCDATA)>

<!ENTITY nombreEditorial "Editorial de libros impresos de la Armuña">

<!--
Entidades externas
<!ENTITY entity-name SYSTEM "ruta">
-->

<!ENTITY textoLegal SYSTEM "./privacidad.txt">
<!ELEMENT documento (contenido,textoLegal)>
<!ELEMENT contenido (#PCDATA)>
<!ELEMENT textoLegal (#PCDATA)>

<!--
Entidades de parámetro
<!ENTITY % nombre "lista de elementos">
-->

<!ENTITY % datosContacto "telefono+, email, direccion">

<!ELEMENT cliente (nombre, %datosContacto;)>
<!ELEMENT proveedor (empresa, %datosContacto;, cif)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT empresa (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT cif (#PCDATA)>

=== lrag/XML/Ej02_DTD/src/main/resources/XML/04_entities.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--  
Referenciamos el DTD
<!DOCTYPE etiqueta_raíz SYSTEM "ruta al DTD">
-->
<!DOCTYPE raiz SYSTEM "04_entities.dtd">

<raiz>

	<libro>
		<editorial>&nombreEditorial;</editorial>
		<autor>Autor1</autor>
	</libro>
	<libro>
		<editorial>&nombreEditorial;</editorial>
		<autor>Autor2</autor>
	</libro>
	<libro>
		<editorial>&nombreEditorial;</editorial>
		<autor>Autor3</autor>
	</libro>
	
	<libro>
		<editorial>Editorial de libros impresos de la Armuña</editorial>
		<autor>Autor1</autor>
	</libro>
	<libro>
		<editorial>Editorial de libros impresos de la Armuña</editorial>
		<autor>Autor2</autor>
	</libro>
	<libro>
		<editorial>Editorial de libros impresos de la Armuña</editorial>
		<autor>Autor3</autor>
	</libro>

	<documento>
		<contenido>Este es el contenido</contenido>
		<textoLegal>&textoLegal;</textoLegal>
	</documento>

	<cliente>
		<nombre>Cliente 1</nombre>
		<telefono>123456789</telefono>
		<email>a@b.c</email>
		<direccion>C/Falsa, 123</direccion>
	</cliente>
	<proveedor>
		<empresa>Empresa 1</empresa>
		
		<telefono>123456789</telefono>
		<telefono>123456789</telefono>
		<telefono>123456789</telefono>
		
		<email>a@b.c</email>
		<direccion>C/Falsa, 123</direccion>
		<cif>987654321</cif>
	</proveedor>

</raiz>
